### PR TITLE
✨ Add support for Python 3.12

### PR DESCRIPTION
**Pull request by shepilov-vladislav**

### CODE REVIEW

**Comment by shepilov-vladislav** [comment]
@tiangolo can it be merged?

**Comment by arsensokolov** [comment]
I'm a waiting...

**Comment by pawarren** [comment]
+1

**Comment by AlexanderSalge** [comment]
does gunicorn even support 3.12 yet? afaik not

**Comment by shepilov-vladislav** [comment]
> does gunicorn even support 3.12 yet? afaik not

https://github.com/benoitc/gunicorn/blob/88fc4a43152039c28096c8ba3eeadb3fbaa4aff9/.github/workflows/tox.yml#L25

Gunicorn supports 3.12 and already tested with 3.12

**Comment by AlexanderSalge** [comment]
good catch, i was just checking pypi and the changelog. maybe tiangolo waiting for a release instead of building from source

**Comment by arks-public** [comment]
+1

It would be extremely useful if the official tiangolo/uvicorn-gunicorn-fastapi supported python3.12

**Comment by CharlesPerrotMinotHCHB** [comment]
Trying a ping @tiangolo

**Comment by coderberry** [comment]
+1

**Comment by z0z0r4** [comment]
+1

**Comment by kaiosatiro** [comment]
+1

**Comment by tiangolo** [comment]
Thank you! :rocket: 

Now that Uvicorn supports managing workers with `--workers`, including restarting dead ones, there's no need for Gunicorn. That also means that it's much simpler to build a Docker image from scratch now, I updated the docs to explain it.

Because of that, I deprecated this Docker image: https://github.com/tiangolo/uvicorn-gunicorn-docker#-warning-you-probably-dont-need-this-docker-image

So I'll pass on this one, but thanks for the effort! :cake:

**Pull request closed without merging**
