### PR TITLE
✨ Add Python 3.9 and Python 3.9 Alpine

### LINKED ISSUE #61: add python 3.9 tag
add python 3.9 tag since it is released.

### PR DESCRIPTION
**Pull request by graue70**
Depends on https://github.com/tiangolo/uvicorn-gunicorn-docker/pull/52.

Fixes #61

### CODE REVIEW

**Comment by brian316** [comment]
waiting for this!

**Comment by fcabaud** [comment]
also waiting for this!

Python 3.9 is the default python version of Ubuntu now.

**Comment by johncox00** [comment]
This would certainly be awesome.

**Comment by jkh911208** [comment]
waiting for this

**Comment by anton-petrov** [comment]
Updated version with latest python 3.9 and/or apline 3.13 => https://hub.docker.com/repository/docker/antonapetrov/uvicorn-gunicorn-fastapi

**Comment by V3K3R** [comment]
We are also waiting for this. but I see that the `python 3.9` builds were not successful.   
I can't see the error logs, so @graue70 do you know why it's failing? and do you need help picking this up?

**Comment by graue70** [comment]
> We are also waiting for this. but I see that the `python 3.9` builds were not successful.
> I can't see the error logs, so @graue70 do you know why it's failing? and do you need help picking this up?

I'm guessing that the builds only failed because https://github.com/tiangolo/uvicorn-gunicorn-docker/pull/52 hasn't been merged yet. I don't think there is anything to do except merging. I can't tell you why @tiangolo doesn't merge or comment on these because I don't know.

**Comment by memark** [comment]
What is the status on this, @tiangolo?

**Comment by tiangolo** [comment]
Thanks for the contribution @graue70! :cake: 

I updated and refactored it a bit, and it's now ready.

Thanks everyone for the interest. This is available now. :rocket: :tada:

**Comment by utkarshgupta137** [comment]
@tiangolo Is it possible for docker images to be built automatically with fastapi releases?

**Pull request merged**
